package com.example.myproject.Navigation

const val ROUT_HOME="home"
const val ROUT_ABOUT="about"
const val ROUT_SPLASH="splash"
const val ROUT_SIGNUP="signup"
const val ROUT_LOGIN="login"
const val ROUT_PRODUCTS="products"
const val ADD_PRODUCTS_URL="add_products"
const val VIEW_PRODUCTS_URL="view_products"
const val ROUT_MEN="men"
const val ROUT_WOMEN="women"
const val ROUT_BABY="baby"
const val ROUT_KIDS="kids"
const val ROUT_MENU="menu"